return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		init = function()
			vim.o.timeout = true
			vim.o.timeoutlen = 300
		end,
		opts = {
			preset = "modern",
			icons = {
				breadcrumb = "»",
				separator = "➜",
				group = "+",
			},
			spec = {
				{ "<leader>f", group = "󰈞 Find/Files" },
				{ "<leader>e", group = "󰙅 Explorer" },
				{ "<leader>g", group = " Git" },
				{ "<leader>l", group = " LSP" },
				{ "<leader>t", group = " Terminal/Tmux" },
				{ "<leader>tp", desc = "Switch tmux panes" },
				{ "<leader>ts", desc = "Switch tmux sessions" },
				{ "<leader>tw", desc = "Switch tmux windows" },
				{ "<leader>w", group = "󰖯 Window" },
				{ "<leader>b", group = "󰓩 Buffer" },
				{ "<leader>y", group = " Yank/Copy" },
				{ "<leader>c", group = " Code/Claude" },
				{ "<leader>cc", desc = "Open Claude Code split" },
				{ "<leader>ct", desc = "Toggle Claude Code pane" },
				{ "<leader>cn", desc = "Create nvim-claude session" },
				{ "<leader>cs", desc = "Symbols (Trouble)" },
				{ "<leader>cS", desc = "LSP refs/defs (Trouble)" },
				{ "<leader>d", group = " Debug" },
				{ "<leader>r", group = " Replace" },
				{ "<leader>s", group = "󰛔 Search" },
				{ "<leader>x", group = "󱍼 Diagnostics/Quickfix" },
				{ "<leader>xd", desc = "Show diagnostic float" },
				{ "<leader>xx", desc = "Diagnostics (Trouble)" },
				{ "<leader>xX", desc = "Buffer diagnostics (Trouble)" },
				{ "<leader>xL", desc = "Location list (Trouble)" },
				{ "<leader>xQ", desc = "Quickfix list (Trouble)" },
				{ "<leader>a", group = "󰚩 AI" },
				{ "g", group = "Goto" },
				{ "gd", desc = "Go to definition" },
				{ "gD", desc = "Peek definitions (Glance)" },
				{ "gi", desc = "Go to implementation" },
				{ "gr", desc = "Go to references" },
				{ "gR", desc = "Peek references (Glance)" },
				{ "gY", desc = "Peek type definitions (Glance)" },
				{ "gM", desc = "Peek implementations (Glance)" },
				{ "go", desc = "Go to type definition" },
				{ "gs", desc = "Signature help" },
				{ "z", group = "Fold" },
				{ "]", group = "Next" },
				{ "]d", desc = "Next diagnostic" },
				{ "]e", desc = "Next error" },
				{ "]w", desc = "Next warning" },
				{ "[", group = "Prev" },
				{ "[d", desc = "Previous diagnostic" },
				{ "[e", desc = "Previous error" },
				{ "[w", desc = "Previous warning" },
			},
		},
	},
}
